// Code generated by "dbusutil-gen em -type StartManager,SessionManager,Inhibitor"; DO NOT EDIT.

package main

import (
	"github.com/linuxdeepin/go-lib/dbusutil"
)

func (v *Inhibitor) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "GetAppId",
			Fn:      v.GetAppId,
			OutArgs: []string{"outArg0"},
		},
		{
			Name:    "GetClientId",
			Fn:      v.GetClientId,
			OutArgs: []string{"outArg0"},
		},
		{
			Name:    "GetFlags",
			Fn:      v.GetFlags,
			OutArgs: []string{"outArg0"},
		},
		{
			Name:    "GetReason",
			Fn:      v.GetReason,
			OutArgs: []string{"outArg0"},
		},
		{
			Name:    "GetToplevelXid",
			Fn:      v.GetToplevelXid,
			OutArgs: []string{"outArg0"},
		},
	}
}
func (v *SessionManager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "AllowSessionDaemonRun",
			Fn:      v.AllowSessionDaemonRun,
			OutArgs: []string{"outArg0"},
		},
		{
			Name:    "CanHibernate",
			Fn:      v.CanHibernate,
			OutArgs: []string{"outArg0"},
		},
		{
			Name:    "CanLogout",
			Fn:      v.CanLogout,
			OutArgs: []string{"outArg0"},
		},
		{
			Name:    "CanReboot",
			Fn:      v.CanReboot,
			OutArgs: []string{"outArg0"},
		},
		{
			Name:    "CanShutdown",
			Fn:      v.CanShutdown,
			OutArgs: []string{"outArg0"},
		},
		{
			Name:    "CanSuspend",
			Fn:      v.CanSuspend,
			OutArgs: []string{"outArg0"},
		},
		{
			Name: "ForceLogout",
			Fn:   v.ForceLogout,
		},
		{
			Name: "ForceReboot",
			Fn:   v.ForceReboot,
		},
		{
			Name: "ForceShutdown",
			Fn:   v.ForceShutdown,
		},
		{
			Name:    "GetInhibitors",
			Fn:      v.GetInhibitors,
			OutArgs: []string{"outArg0"},
		},
		{
			Name:    "Inhibit",
			Fn:      v.Inhibit,
			InArgs:  []string{"appId", "toplevelXid", "reason", "flags"},
			OutArgs: []string{"inhibitCookie"},
		},
		{
			Name:    "IsInhibited",
			Fn:      v.IsInhibited,
			InArgs:  []string{"flags"},
			OutArgs: []string{"outArg0"},
		},
		{
			Name: "Logout",
			Fn:   v.Logout,
		},
		{
			Name: "PowerOffChoose",
			Fn:   v.PowerOffChoose,
		},
		{
			Name: "Reboot",
			Fn:   v.Reboot,
		},
		{
			Name:    "Register",
			Fn:      v.Register,
			InArgs:  []string{"id"},
			OutArgs: []string{"outArg0"},
		},
		{
			Name: "RequestHibernate",
			Fn:   v.RequestHibernate,
		},
		{
			Name: "RequestLock",
			Fn:   v.RequestLock,
		},
		{
			Name: "RequestLogout",
			Fn:   v.RequestLogout,
		},
		{
			Name: "RequestReboot",
			Fn:   v.RequestReboot,
		},
		{
			Name: "RequestShutdown",
			Fn:   v.RequestShutdown,
		},
		{
			Name: "RequestSuspend",
			Fn:   v.RequestSuspend,
		},
		{
			Name:   "SetLocked",
			Fn:     v.SetLocked,
			InArgs: []string{"value"},
		},
		{
			Name: "Shutdown",
			Fn:   v.Shutdown,
		},
		{
			Name: "ToggleDebug",
			Fn:   v.ToggleDebug,
		},
		{
			Name:   "Uninhibit",
			Fn:     v.Uninhibit,
			InArgs: []string{"inhibitCookie"},
		},
	}
}
func (v *StartManager) GetExportedMethods() dbusutil.ExportedMethods {
	return dbusutil.ExportedMethods{
		{
			Name:    "AddAutostart",
			Fn:      v.AddAutostart,
			InArgs:  []string{"filename"},
			OutArgs: []string{"outArg0"},
		},
		{
			Name:    "AutostartList",
			Fn:      v.AutostartList,
			OutArgs: []string{"outArg0"},
		},
		{
			Name:    "DumpMemRecord",
			Fn:      v.DumpMemRecord,
			OutArgs: []string{"outArg0"},
		},
		{
			Name:    "GetApps",
			Fn:      v.GetApps,
			OutArgs: []string{"outArg0"},
		},
		{
			Name:    "IsAutostart",
			Fn:      v.IsAutostart,
			InArgs:  []string{"filename"},
			OutArgs: []string{"outArg0"},
		},
		{
			Name:    "IsMemSufficient",
			Fn:      v.IsMemSufficient,
			OutArgs: []string{"outArg0"},
		},
		{
			Name:    "Launch",
			Fn:      v.Launch,
			InArgs:  []string{"desktopFile"},
			OutArgs: []string{"outArg0"},
		},
		{
			Name:   "LaunchApp",
			Fn:     v.LaunchApp,
			InArgs: []string{"desktopFile", "timestamp", "files"},
		},
		{
			Name:   "LaunchAppAction",
			Fn:     v.LaunchAppAction,
			InArgs: []string{"desktopFile", "action", "timestamp"},
		},
		{
			Name:   "LaunchAppWithOptions",
			Fn:     v.LaunchAppWithOptions,
			InArgs: []string{"desktopFile", "timestamp", "files", "options"},
		},
		{
			Name:    "LaunchWithTimestamp",
			Fn:      v.LaunchWithTimestamp,
			InArgs:  []string{"desktopFile", "timestamp"},
			OutArgs: []string{"outArg0"},
		},
		{
			Name:    "RemoveAutostart",
			Fn:      v.RemoveAutostart,
			InArgs:  []string{"filename"},
			OutArgs: []string{"outArg0"},
		},
		{
			Name:   "RunCommand",
			Fn:     v.RunCommand,
			InArgs: []string{"exe", "args"},
		},
		{
			Name:   "RunCommandWithOptions",
			Fn:     v.RunCommandWithOptions,
			InArgs: []string{"exe", "args", "options"},
		},
		{
			Name:   "TryAgain",
			Fn:     v.TryAgain,
			InArgs: []string{"launch"},
		},
	}
}
