diff --git a/Makefile b/Makefile
index e0db39a..4b9d75a 100644
--- a/Makefile
+++ b/Makefile
@@ -52,8 +52,8 @@ install:
 	install -v -m0644 misc/config/* ${DESTDIR}${PREFIX}/share/startdde/
 	install -v -m0644 misc/app_startup.conf ${DESTDIR}${PREFIX}/share/startdde/
 	install -v -m0644 misc/filter.conf ${DESTDIR}${PREFIX}/share/startdde/
-	mkdir -p ${DESTDIR}/etc/X11/Xsession.d/
-	install -v -m0644 misc/Xsession.d/* ${DESTDIR}/etc/X11/Xsession.d/
+	mkdir -p ${DESTDIR}/etc/X11/xinit/xinitrc.d/
+	cp -f misc/Xsession.d/* ${DESTDIR}/etc/X11/xinit/xinitrc.d/
 	mkdir -p ${DESTDIR}/etc/profile.d/
 	install -v -m0644 misc/profile.d/* ${DESTDIR}/etc/profile.d/
 	mkdir -p $(DESTDIR)$(PREFIX)/share/glib-2.0/schemas
