--- Makefile.orig	2020-09-17 21:16:11.810066617 +0800
+++ Makefile	2020-09-17 21:16:46.166065869 +0800
@@ -47,8 +47,8 @@
 	install -Dm644 misc/lightdm.conf ${DESTDIR}${PREFIX}/share/lightdm/lightdm.conf.d/60-deepin.conf
 	mkdir -p ${DESTDIR}${PREFIX}/share/startdde/
 	cp -f misc/config/* ${DESTDIR}${PREFIX}/share/startdde/
-	mkdir -p ${DESTDIR}/etc/X11/Xsession.d/
-	cp -f misc/Xsession.d/* ${DESTDIR}/etc/X11/Xsession.d/
+	mkdir -p ${DESTDIR}/etc/X11/xinit/xinitrc.d/
+	cp -f misc/Xsession.d/* ${DESTDIR}/etc/X11/xinit/xinitrc.d/
 	mkdir -p ${DESTDIR}/etc/profile.d/
 	cp -f misc/profile.d/* ${DESTDIR}/etc/profile.d/
 
