.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 wubowen <wubowen@uniontech.com>,
.\"
.TH "deepin-fix-xauthority-perm" "1" "2021-3-29" "Deepin"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
deepin-fix-xauthority-perm \- Repair .Xauthority filemode.
.SH SYNOPSIS
deepin-fix-xauthority-perm
.SH DESCRIPTION
Deepin Fix Xauthority Perm binary.
.PP
Deepin Fix Xauthority Perm is the control panel of Deepin Desktop Environment.
.SH OPTIONS
.PP
-h   show help info
.SH SEE ALSO
https://github.com/linuxdeepin/startdde
.SH AUTHOR
.PP
.B deepin-fix-xauthority-perm
is written by Deepin Technology Co., Ltd.
.PP
This manual page was written by
.MT wubowen@\:uniontech.com
Wu Bo Wen
